#########################
# StarDock Compose File #
#########################

version: '3'

services:

  # Reverse Proxy
  ################

  # Traefik

  proxy:
    image: traefik
    container_name: Traefik
    command: --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ${DSOCK}:/var/run/docker.sock
      - ./configs/traefik.toml:/traefik.toml

  # Management Tools
  ###################

  # WatchTower

  watchtower:
    image: v2tec/watchtower
    container_name: "Watchtower"
    restart: unless-stopped
    command: --cleanup --interval 43200
    networks:
      - webgateway
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_NOTIFICATION_EMAIL_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_NOTIFICATION_EMAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}
    volumes:
      - ${DSOCK}:/var/run/docker.sock

  # Portrainer

  portainer:
    image: portainer/portainer
    container_name: Portainer
    restart: unless-stopped
    networks:
      - webgateway
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=PathPrefixStrip: /portainer/"
    volumes:
      - ${PORTAINER_DATA_PATH}:/data
      - ${DSOCK}:/var/run/docker.sock

  # Media Servers
  ################

  # Plex
  plex:
    image: linuxserver/plex 
    container_name: "ArchPlex"
    # hostname: "ArchPlexDocker"
    restart: unless-stopped
    network_mode: host
    # networks:
    #   - webgateway
    # labels:
    #   - "traefik.backend=plex"
    #   - "traefik.port=32400"
    #   - "traefik.frontend.rule=PathPrefixStrip: /plex/"
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PLEX_TRANSCODE_PATH}:/transcode
      - ${PLEX_LOGS_PATH}:/logs
      - ${PLEX_TV_PATH}:/data/Storage/TV
      - ${PLEX_ANIME_PATH}:/data/Storage/Anime
      - ${PLEX_MOVIES_PATH}:/data/Storage/Movies
      - ${PLEX_VIDEOS_PATH}:/data/Storage/Videos
      - ${PLEX_EXTRA_TV_PATH}:/data/Xiaomi/TV
      - ${PLEX_EXTRA_ANIME_PATH}:/data/Xiaomi/Anime
      - ${PLEX_EXTRA_MOVIES_PATH}:/data/Xiaomi/Movies
      - ${PLEX_EXTRA_VIDEOS_PATH}:/data/Xiaomi/Videos

  # PlexPy
  plexpy:
    image: linuxserver/plexpy:latest
    networks:
      - webgateway
    volumes:
      - ${PLEXPY_CONFIG_PATH}:/config
      - ${PLEX_LOGS_PATH}:/logs
    labels:
      - "traefik.backend=plexpy"
      - "traefik.frontend.rule=PathPrefixStrip: /plexpy/"
      - "traefik.port=8181"
    depends_on:
      - plex

networks:
    webgateway:
      driver: bridge