#########################
# StarDock Compose File #
#########################

version: '3'

services:

  # Reverse Proxy
  ################

  # Nginx with amplify and permissions for organizr

  proxy:
    image: haozeke/docker_nginx_amplify_alpine
    container_name: Nginx
    networks:
      - webgateway
    ports:
      - "80:80"
    environment:
      - API_KEY=${AMPLIFY_API_KEY}
      - AMPLIFY_IMAGENAME="ArchDocker"
    depends_on:
      - portainer
      - plex
      - plexpy
      - caliweb
    volumes:
      - ${DSOCK}:/var/run/docker.sock
      - ./configs/nginx:/etc/nginx
      - ${ORGANIZR_CONFIG_PATH}:/config
      - ${WEBAPP_PATH}:/www

  php:
    image: haozeke/php_zip_alpine
    container_name: php
    networks:
      - webgateway
    volumes:
      - ${ORGANIZR_CONFIG_PATH}:/config
      - ${WEBAPP_PATH}:/www  


  # Management Tools
  ###################

  # WatchTower

  watchtower:
    image: v2tec/watchtower
    container_name: "Watchtower"
    restart: unless-stopped
    command: --cleanup --interval 43200
    networks:
      - webgateway
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_NOTIFICATION_EMAIL_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_NOTIFICATION_EMAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}
    volumes:
      - ${DSOCK}:/var/run/docker.sock

  # Portrainer

  portainer:
    image: portainer/portainer
    container_name: Portainer
    restart: unless-stopped
    ports:
      - 4600:9000
    networks:
      - webgateway
    expose:
      - 9000
    volumes:
      - ${PORTAINER_DATA_PATH}:/data
      - ${DSOCK}:/var/run/docker.sock

  # Media Servers
  ################

  # Plex
  plex:
    image: linuxserver/plex 
    container_name: "ArchPlex"
    hostname: "ArchPlexDocker"
    restart: unless-stopped
    # network_mode: host
    networks:
      - webgateway
    expose:
      - 32400
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PLEX_TRANSCODE_PATH}:/transcode
      - ${PLEX_LOGS_PATH}:/logs
      - ${PLEX_TV_PATH}:/data/Storage/TV
      - ${PLEX_ANIME_PATH}:/data/Storage/Anime
      - ${PLEX_MOVIES_PATH}:/data/Storage/Movies
      - ${PLEX_VIDEOS_PATH}:/data/Storage/Videos
      - ${PLEX_EXTRA_TV_PATH}:/data/Xiaomi/TV
      - ${PLEX_EXTRA_ANIME_PATH}:/data/Xiaomi/Anime
      - ${PLEX_EXTRA_MOVIES_PATH}:/data/Xiaomi/Movies
      - ${PLEX_EXTRA_VIDEOS_PATH}:/data/Xiaomi/Videos

  # # Emby
  # emby:
  #   image: nvllsvm/emby-unlocked
  #   container_name: "ArchEmby"
  #   hostname: "ArchEmbyDocker"
  #   restart: unless-stopped
  #   # network_mode: host
  #   networks:
  #     - webgateway
  #   expose:
  #     - 8096
  #   volumes:
  #     - ${EMBY_CONFIG_PATH}:/config
  #     - ${EMBY_TRANSCODE_PATH}:/transcode
  #     - ${EMBY_TV_PATH}:/media/Storage/TV
  #     - ${EMBY_ANIME_PATH}:/media/Storage/Anime
  #     - ${EMBY_MOVIES_PATH}:/media/Storage/Movies
  #     - ${EMBY_VIDEOS_PATH}:/media/Storage/Videos
  #     - ${EMBY_EXTRA_TV_PATH}:/media/Xiaomi/TV
  #     - ${EMBY_EXTRA_ANIME_PATH}:/media/Xiaomi/Anime
  #     - ${EMBY_EXTRA_MOVIES_PATH}:/media/Xiaomi/Movies
  #     - ${EMBY_EXTRA_VIDEOS_PATH}:/media/Xiaomi/Videos

  # Calibre web
  caliweb:
    image: technosoft2000/calibre-web
    container_name: "CalibreWeb"
    networks:
      - webgateway
    expose:
      - 8083
    environment:
      - USE_CONFIG_DIR=true
    volumes:
      - ${CALIBRE_APP_PATH}:/calibre-web
      - ${CALIBRE_LIBRARY_PATH}:/books

  # Airsonic
  airsonic:
    image: linuxserver/airsonic
    container_name: "Airsonic"
    networks:
      - webgateway
    expose:
      - 4040
    environment:
      - CONTEXT_PATH=/airsonic
    volumes:
      - ${MUSIC_CONFIG_PATH}:/config
      - ${MUSIC_LIBRARY_PATH}:/music
      - ${MUSIC_PLAYLISTS_PATH}:/playlists
      - ${MUSIC_PODCASTS_PATH}:/podcasts
      - ${MUSIC_MEDIA_PATH}:/media

  # # MPD Icecast YMPD

  # icecast:
  #   image: vitiman/alpine-icecast:latest
  #   container_name: "Icecast"
  #   ports:
  #     - "8000:8000"
  #   expose:
  #     - 8000
  #   networks:
  #     - webgateway

  # # Add your host volumen in path/to/... or add your own volume below
  # mpd:
  #   image: vitiman/alpine-mpd:latest
  #   container_name: "MPD"
  #   ports:
  #     - "6600:6600"
  #   expose:
  #     - 6600
  #   depends_on:
  #     - icecast
  #   networks:
  #     - webgateway
  #   volumes:
  #     - ${MUSIC_LIBRARY_PATH}:/var/lib/mpd/music
  #     - ${MPD_PLAYLISTS_PATH}:/var/lib/mpd/playlists
  #     - ${MPD_DB_PATH}:/var/lib/mpd/database

  # sima:
  #   image: vitiman/alpine-sima:latest
  #   container_name: "SIMA"
  #   depends_on:
  #     - mpd
  #   networks:
  #     - webgateway

  # ympd:
  #   image: vitiman/alpine-ympd:latest
  #   container_name: "YMPD"
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - 8080
  #   depends_on:
  #     - mpd
  #   networks:
  #     - webgateway 

  # # Interface and Backends
  # ##########################

  # PlexPy [Stats]
  plexpy:
    image: linuxserver/plexpy:latest
    container_name: "PlexPy"
    networks:
      - webgateway
    expose:
      - 8181
    volumes:
      - ${PLEXPY_CONFIG_PATH}:/config
      - ${PLEX_LOGS_PATH}:/logs
    depends_on:
      - plex

  # Ombi [Requests]
  ombi:
    image: linuxserver/ombi:latest
    container_name: "Ombi"
    networks:
      - webgateway
    expose:
      - 3579
    volumes:
      - ${OMBI_CONFIG_PATH}:/config
    depends_on:
      - plex

  # Jackett [Tracker Aggregation]
  jackett:
    image: linuxserver/jackett:latest
    container_name: "Jackett"
    networks:
      - webgateway
    expose:
      - 9117
    volumes:
      - ${JACKETT_CONFIG_PATH}:/config
      - ${TRANSMISSION_DOWNLOAD_PATH}:/downloads

  # Transmission [Torrents]
  transmission:
    image: linuxserver/transmission:latest
    container_name: "Transmission"
    networks:
      - webgateway
    expose:
      - 9091
    volumes:
      - ${TRANSMISSION_CONFIG_PATH}:/config
      - ${TRANSMISSION_WATCH_PATH}:/watch
      - ${TRANSMISSION_DOWNLOAD_PATH}:/downloads

  # Sabnzbd [Usenet]
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: "Sabnzbd"
    networks:
      - webgateway
    expose:
      - 8080
    volumes:
      - ${SAB_CONFIG_PATH}:/config
      - ${SAB_INC_DOWN_PATH}:/incomplete-downloads
      - ${SAB_DOWNLOAD_PATH}:/downloads

  # Radarr [Movies]
  radarr:
    image: linuxserver/radarr:latest
    container_name: "Radarr"
    networks:
      - webgateway
    expose:
      - 7878
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${PLEX_MOVIES_PATH}:/movies
      - ${TRANSMISSION_DOWNLOAD_PATH}:/downloads
    depends_on:
      - transmission

  # Sonarr [TV Stuff]
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: "Sonarr"
    networks:
      - webgateway
    expose:
      - 8989
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${PLEX_TV_PATH}:/tv
      - ${PLEX_ANIME_PATH}:/anime
      - ${TRANSMISSION_DOWNLOAD_PATH}:/downloads
    depends_on:
      - transmission

  # Headphones [Music Stuff]
  headphones:
    image: linuxserver/headphones:latest
    container_name: "Headphones"
    networks:
      - webgateway
    expose:
      - 8181
    volumes:
      - ${HEADPHONES_CONFIG_PATH}:/config
      - ${TRANSMISSION_DOWNLOAD_PATH}:/downloads
      - ${MUSIC_LIBRARY_PATH}:/music
    depends_on:
      - transmission

  # LazyLibrarian [Book Stuff]
  lazylib:
    image: linuxserver/lazylibrarian:latest
    container_name: "LazyLibrarian"
    networks:
      - webgateway
    expose:
      - 5299
    volumes:
      - ${LAZYLIB_CONFIG_PATH}:/config
      - ${TRANSMISSION_DOWNLOAD_PATH}:/downloads
      - ${CALIBRE_LIBRARY_PATH}:/books
    depends_on:
      - transmission

networks:
    webgateway:
      driver: bridge